name: tarjumaquran
description: A new Flutter application.

version: 3.0.6+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6+1
  fluttertoast: ^3.1.3
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1
  screen: ^0.0.5

  flutter_svg: ^0.16.1
  webview_flutter: ^0.3.19+5
  path_provider: 1.6.1
  sqflite: ^1.2.1
  flutter_typeahead: ^1.8.0
  progress_dialog: ^1.2.0
  cupertino_icons: ^0.1.2
  custom_switch: ^0.0.1
  share: ^0.6.3+6
  launch_review: ^2.0.0
  flutter_html: ^0.8.2
  url_launcher: ^5.4.2
  substring_highlight: ^0.1.2
  scrollable_positioned_list: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/tarjuma.db

  fonts:
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf

    - family: NooreHuda
      fonts:
        - asset: assets/fonts/noorehuda.ttf

    - family: Saleem
      fonts:
        - asset: assets/fonts/pdms.ttf