name: tarjumaquran
description: A new Flutter application.

version: 3.0.7+9

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^1.0.4
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  screens: ^2.5.0
  get: ^4.6.1

  flutter_svg: ^0.22.0
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  flutter_typeahead: ^3.2.4
  cupertino_icons: ^1.0.4
  share: ^2.0.4
  launch_review: ^3.0.1
  flutter_html: ^2.2.1
  url_launcher: ^6.0.20
  visibility_detector: ^0.2.2
  scrollable_positioned_list: ^0.2.3
  flutter_parsed_text: ^2.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/tarjuma.db

  fonts:
    - family: Jameel
      fonts:
        - asset: assets/fonts/jameel.ttf

    - family: NooreHuda
      fonts:
        - asset: assets/fonts/noorehuda.ttf

    - family: Saleem
      fonts:
        - asset: assets/fonts/pdms.ttf